### ISSUE TITLE
adf-core.jar -compile is not working

### ISSUE THREAD

**Issue by mhrimaz** [RCRS-ADF/sample#1]
I am running this command:
java -jar ./library/rescue/adf/adf-core.jar -compile
but I'm getting this error:
[ RCRS ADF Version 2.2.0 (build 20170213T054156Z) ]

[START ] Agent compile
[INFO  ] Working directory: /home/hossein/rescue/adf-sample
[FINISH] Agent compile
[START ] Agent class check
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at adf.launcher.LaunchSupporter.checkAgentClass(LaunchSupporter.java:468)
	at adf.launcher.LaunchSupporter.checkAgentClass(LaunchSupporter.java:496)
	at adf.launcher.LaunchSupporter.checkAgentClass(LaunchSupporter.java:496)
	at adf.launcher.LaunchSupporter.checkAgentClass(LaunchSupporter.java:496)
	at adf.launcher.LaunchSupporter.checkAgentClass(LaunchSupporter.java:305)
	at adf.launcher.LaunchSupporter.delegate(LaunchSupporter.java:97)
	at adf.Main.main(Main.java:21)
____________________________________________________________
java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
Linux Ubuntu 16.04

**Comment by tkmnet** [comment]
I am sorry. I can not estimate that situation.
Would you replace adf-core.jar for following jar, and send a output that re-execute the command.
http://aitech.ac.jp/maslab/~takamin/adf-core.jar
Thank you in advance.

**Comment by mhrimaz** [comment]
I replaced it but still not working. This is the output:

java -jar ./library/rescue/adf/adf-core.jar -compile
[ RCRS ADF Version 2.2.0 (build 20170322T160354Z) ]

[START ] Agent compile
[INFO  ] Working directory: /home/hossein/rescue/adf-sample
[FINISH] Agent compile
[START ] Agent class check
[ERROR ] Unexpected class name (build ->)

**Comment by tkmnet** [comment]
I improved the code to avoid that problem.
Would you execute following command and retry.
```
java -jar ./library/rescue/adf/adf-core.jar -updatecore
```
Thank you for your report and cooperation.

**Comment by mhrimaz** [comment]
Thank you for your response. It is now working.

java -jar ./library/rescue/adf/adf-core.jar -updatecore
[ RCRS ADF Version 2.2.0 (build 20170213T054156Z) ]

[START ] Download jars
[FINISH] Download jars

and after that

java -jar ./library/rescue/adf/adf-core.jar -compile
[ RCRS ADF Version 2.2.0 (build 20170322T185039Z) ]

[START ] Agent compile
[INFO  ] Working directory: /home/hossein/rescue/adf-sample
[FINISH] Agent compile
[START ] Agent class check
[FINISH] Agent class check (0 warning)
