### ISSUE TITLE
The MessageTool can't send request message

### ISSUE THREAD

**Issue by CuiRj** [RCRS-ADF/sample#4]
I think it should be || in line 133 of MessageTool.java otherwise the program can't jump to this branch. 
`
public void sendRequestMessages (AgentInfo agentInfo, WorldInfo worldInfo, ScenarioInfo scenarioInfo, MessageManager messageManager)
    {

        if (agentInfo.me().getStandardURN() == AMBULANCE_TEAM
                && agentInfo.me().getStandardURN() == FIRE_BRIGADE)
`

**Comment by tkmnet** [comment]
Thank you for your report.
I fixed it.
